name: build-rp2040

on:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/build-rp2040.yml'
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -x -e -o pipefail {0}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib srecord

      - name: Build feather only
        working-directory: firmware
        run: |
          mkdir build-feather
          cd build-feather
          PICO_BOARD=feather_host cmake ..
          make -j$(nproc)
          mkdir -p ../../artifacts
          cp remapper.uf2 ../../artifacts/remapper_feather.uf2
          cp remapper_auto.uf2 ../../artifacts/remapper_auto_feather.uf2

      - uses: actions/upload-artifact@v4
        with:
          name: firmware-rp2040
          path: artifacts/*.uf2